object Versions {
    const val room = "2.4.2"
    const val hilt = "2.42"
    const val dagger2 = "2.42"
    const val viewModelKtx = "2.5.0-rc01"
    const val lifecycleRuntimeKtx = "2.5.0-rc01"
    const val fragmentKtx = "1.4.1"
    const val coroutines = "1.6.1"
    const val dateTime = "0.3.2"
    const val androidCore = "1.7.0"
    const val legacySupport = "1.0.0"
    const val recyclerView = "1.2.1"
    const val appCompat = "1.4.1"
    const val material = "1.6.0"
    const val constraintLayout = "2.1.4"
    const val gson = "2.9.0"
    const val retrofit2 = "2.9.0"
    const val loggingInterceptor = "4.9.3"
    const val navigation = "2.4.2"
    const val safeArgs = "2.4.2"
    const val coil = "2.1.0"

    const val junit = "4.13.2"
    const val mockK = "1.12.4"
    const val coroutineTest = "1.6.2"
    const val androidTestJUnitExt = "1.1.3"
}